### ISSUE TITLE
კატეგორიებით გაფილრვა

### ISSUE THREAD

**Issue by zura03geolab** [developer--/PROJECT_MAKE_A_PRESENT#4]
ჯემო, ვერ გავაკეთე კატეგორიებით გაფილტრვა და იქნებ მითითება მომცე.

**Comment by developer--** [comment]
ჩავასწორე კატეგორიების გაფილტვრა და გადახედე კარგად

**Comment by zura03geolab** [comment]
გადავხედავ აუცილებლად.
